"""Public model types for ComfyGit Core."""
# pyright: reportUnsupportedDunderAll=false

from importlib import import_module
from typing import Any

_EXPORTS: dict[str, str] = {
    "ComfyDockError": "exceptions",
    "CDWorkspaceError": "exceptions",
    "CDWorkspaceNotFoundError": "exceptions",
    "CDWorkspaceExistsError": "exceptions",
    "CDCredentialStoreError": "exceptions",
    "CDEnvironmentError": "exceptions",
    "CDEnvironmentNotFoundError": "exceptions",
    "CDEnvironmentExistsError": "exceptions",
    "CDDependencyPreviewStaleError": "exceptions",
    "CDDependencyConflictError": "exceptions",
    "CDExportError": "exceptions",
    "CDNodeNotFoundError": "exceptions",
    "CDNodeConflictError": "exceptions",
    "CDResolutionError": "exceptions",
    "CDRegistryError": "exceptions",
    "CDRegistryDataError": "exceptions",
    "CDRegistryAuthError": "exceptions",
    "CDRegistryServerError": "exceptions",
    "CDRegistryConnectionError": "exceptions",
    "CDProcessError": "exceptions",
    "CDPyprojectError": "exceptions",
    "CDPyprojectNotFoundError": "exceptions",
    "CDPyprojectInvalidError": "exceptions",
    "CDDependencyError": "exceptions",
    "CDPackageSyncError": "exceptions",
    "CDIndexError": "exceptions",
    "UVCommandError": "exceptions",
    "UVNotInstalledError": "exceptions",
    "NodeAction": "exceptions",
    "NodeConflictContext": "exceptions",
    "DependencyConflictContext": "exceptions",
    "DownloadErrorContext": "exceptions",
    "CDModelDownloadError": "exceptions",
    "EnvironmentStatus": "environment",
    "GitStatus": "environment",
    "GitInfo": "environment",
    "GitBranch": "git",
    "GitCommitSummary": "git",
    "GitRemote": "git",
    "GitRemoteBranch": "git",
    "GitRemoteRefs": "git",
    "GitRemoteTag": "git",
    "GitSyncStatus": "git",
    "EnvironmentComparison": "environment",
    "MissingModelInfo": "environment",
    "ChangesSummary": "environment",
    "PackageSyncStatus": "environment",
    "NodeInfo": "shared",
    "NodeDevLinkResult": "shared",
    "ModelInfo": "shared",
    "ModelIndexSource": "shared",
    "ModelIndexStats": "shared",
    "ModelLocation": "shared",
    "ModelWithLocation": "shared",
    "ModelDetails": "shared",
    "ModelDeleteResult": "shared",
    "EnvironmentDependency": "resource_inventory",
    "EnvironmentInventory": "resource_inventory",
    "ModelDeletionApplyResult": "resource_inventory",
    "ModelDeletionPlan": "resource_inventory",
    "ModelInventoryEntry": "resource_inventory",
    "ModelSource": "resource_inventory",
    "StorageSummary": "resource_inventory",
    "WorkspaceInventory": "resource_inventory",
    "ModelWithoutSourceInfo": "shared",
    "LegacyCleanupResult": "shared",
    "NodePackage": "shared",
    "UpdateResult": "shared",
    "NodeRemovalResult": "shared",
    "ManagerStatus": "shared",
    "ManagerUpdateResult": "shared",
    "ScanResult": "model_scan",
    "ModelScanProgress": "model_scan",
    "ModelSourceStatus": "shared",
    "ModelSourceResult": "shared",
    "OverlayConfig": "overlay",
    "OverlayInfo": "overlay",
    "SyncResult": "sync",
    "UVSyncOutcome": "sync",
    "APICredentials": "workspace_config",
    "ModelDirectory": "workspace_config",
    "WorkspaceConfig": "workspace_config",
    "CredentialMigrationResult": "credentials",
    "CredentialProvider": "credentials",
    "CredentialSource": "credentials",
    "CredentialStatus": "credentials",
    "CredentialStore": "credentials",
    "MemoryCredentialStore": "credentials",
    "EnvironmentManifestSnapshot": "manifest",
    "ManifestProjectSnapshot": "manifest",
    "ManifestUVSnapshot": "manifest",
    "ManifestWorkflowEntry": "manifest",
    "ManifestModel": "manifest",
    "ManifestWorkflowModel": "manifest",
    "EnvironmentLifecycleStatus": "lifecycle",
    "LifecycleAction": "lifecycle",
    "LifecycleActionID": "lifecycle",
    "LifecycleIssue": "lifecycle",
    "LifecycleIssueID": "lifecycle",
    "LifecycleLayer": "lifecycle",
    "LifecycleLayerStatus": "lifecycle",
    "LifecycleLayerSummary": "lifecycle",
    "LifecycleOperationState": "lifecycle",
    "LifecycleRuntimeState": "lifecycle",
    "LifecycleSeverity": "lifecycle",
    "MaterializeOptions": "materialization",
    "MaterializeResult": "materialization",
    "DependencyResolutionPreview": "dependency_resolution",
    "DependencyResolutionAcceptance": "dependency_resolution",
    "DependencyResolutionApplyResult": "dependency_resolution",
    "PackageVersionChange": "dependency_resolution",
    "ModelResolutionRequest": "commit",
    "RefDiff": "ref_diff",
    "WorkflowConflict": "ref_diff",
    "NodeConflict": "ref_diff",
    "DependencyConflict": "ref_diff",
    "NodeChange": "ref_diff",
    "ModelChange": "ref_diff",
    "WorkflowChange": "ref_diff",
    "DependencyChanges": "ref_diff",
    "MergeResult": "merge_plan",
    "MergeValidation": "merge_plan",
    "NodeVersionConflict": "merge_plan",
    "WorkflowContractInput": "workflow_contract",
    "WorkflowContractInputControl": "workflow_contract",
    "WorkflowContractOutput": "workflow_contract",
    "NamedWorkflowContract": "workflow_contract",
    "WorkflowExecutionContract": "workflow_contract",
    "ComfyUIPrompt": "workflow_execution",
    "ContractOutputArtifact": "workflow_execution",
    "ContractOutputResult": "workflow_execution",
    "PromptAppliedInput": "workflow_execution",
    "PromptBuildIssue": "workflow_execution",
    "ContractPromptBuildResult": "workflow_execution",
    "BuildAssetCatalog": "build_readiness",
    "BuildCustomNodeSummary": "build_readiness",
    "BuildDependencyKind": "build_readiness",
    "BuildDependencyProof": "build_readiness",
    "BuildDependencyStatus": "build_readiness",
    "BuildModelSummary": "build_readiness",
    "BuildReadiness": "build_readiness",
    "BuildReadinessStatus": "build_readiness",
    "BuildSourceValidationResult": "build_readiness",
    "BuildSourceValidator": "build_readiness",
    "BuildWorkflowContractIOSummary": "build_readiness",
    "BuildWorkflowContractSummary": "build_readiness",
    "BuildWorkflowSummary": "build_readiness",
    "DependencyCriticality": "readiness",
    "EnvironmentReadiness": "readiness",
    "ModelSourceCandidate": "readiness",
    "ModelSourceWarning": "readiness",
    "NodeProvenanceWarning": "readiness",
    "ReadinessBlockingIssue": "readiness",
    "ReadinessBlockingIssueType": "readiness",
    "ReadinessContext": "readiness",
    "ReadinessEnvironment": "readiness",
    "ReadinessGitStatusReader": "readiness",
    "ReadinessModelSourceReader": "readiness",
    "ReadinessWorkflowStatus": "readiness",
    "ReadinessWorkflowSyncStatus": "readiness",
    "ReadinessWorkflowStatusReader": "readiness",
    "ReadinessWarnings": "readiness",
    "DependencyGroupRemovalResult": "runtime_config",
    "OverlayActivationResult": "runtime_config",
    "OverlayTemplateResult": "runtime_config",
    "TorchBackendDetection": "runtime_config",
    "TorchBackendSelection": "runtime_config",
    "TorchBackendStatus": "runtime_config",
    "UVCommandContext": "runtime_config",
    "NodeRegistryLookup": "unmanaged_import",
    "UnmanagedComfyUIImportPreview": "unmanaged_import",
    "UnmanagedComfyUIImportResult": "unmanaged_import",
    "UnmanagedCustomNodeScan": "unmanaged_import",
    "UnmanagedDevelopmentNodeLink": "unmanaged_import",
    "UnmanagedImportCallbacks": "unmanaged_import",
    "UnmanagedModelReferenceScan": "unmanaged_import",
    "UnmanagedWorkflowScan": "unmanaged_import",
    "BatchDownloadCallbacks": "workflow",
    "NodeInstallCallbacks": "workflow",
    "ModelResolutionContext": "workflow",
    "NodeResolutionContext": "workflow",
    "ResolvedModel": "workflow",
    "ResolvedNodePackage": "workflow",
    "ScoredMatch": "workflow",
    "ScoredPackageMatch": "workflow",
    "WorkflowNodeWidgetRef": "workflow",
    "WorkflowAnalysisStatus": "workflow",
    "WorkflowDependencies": "workflow",
    "WorkflowSyncStatus": "workflow",
    "DetailedWorkflowStatus": "workflow",
    "ResolutionResult": "workflow",
    "Workflow": "workflow",
    "NodeResolutionStrategy": "protocols",
    "ModelResolutionStrategy": "protocols",
    "RollbackStrategy": "protocols",
    "SyncCallbacks": "protocols",
    "ImportCallbacks": "protocols",
    "ExportCallbacks": "protocols",
    "EnvironmentCreateProgress": "protocols",
    "ConflictResolver": "protocols",
}

__all__ = sorted(_EXPORTS)


def __getattr__(name: str) -> Any:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f"{__name__}.{module_name}")
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
